# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "zs_unittest")

oncall("data_compression")

zs_unittest(
    name = "test",
    srcs = [
        "test_json_lex.cpp",
    ],
    deps = [
        "..:json_parser",
        "../../../cpp:openzl_cpp",
    ],
)
